build:
  image: bjodah/bjodahimg16dev:v1.3
  environment:
    - CPLUS_INCLUDE_PATH=/opt/boost_1_65_0/include
    - LIBRARY_PATH=/opt/boost_1_65_0/lib
    - LD_LIBRARY_PATH=/opt/boost_1_65_0/lib
  commands:
    - echo "#error" >/opt/boost_1_65_0/include/boost/numeric/odeint/stepper/rosenbrock4_controller.hpp
    - PYCVODES_LAPACK=lapack,blas ./scripts/ci.sh pyodesys
    - ./scripts/prepare_deploy.sh
    - rm -r ~/.cache/python*pyodesys*/
    - PATH=/opt/miniconda3/bin:$PATH conda config --add channels bjodah  # sym, pyodesys, pyneqsys
    - PATH=/opt/miniconda3/bin:$PATH conda build conda-recipe
    - bash -c '[[ $(python setup.py --version) =~ ^[0-9]+.* ]]'
    - ./scripts/grep-for-merge-blocking-token.sh

deploy:

  rsync:
    host: hera.physchem.kth.se
    port: 22
    user: pyodesys
    source: deploy/
    target: ~
    recursive: true
    delete: false
