build:
  image: bjodah/bjodahimg16dev:latest
  commands:
    - conda config --add channels symengine/label/dev
    - conda config --add channels bjodah
    - ./scripts/ci.sh pyodesys
    - ./scripts/render_notebooks.sh
    - python -m pip install .[docs]
    - ./scripts/generate_docs.sh
    - ./scripts/prepare_deploy.sh

deploy:

  rsync:
    host: hera.physchem.kth.se
    port: 22
    user: pyodesys
    source: deploy/
    target: ~
    recursive: true
    delete: false
