image: bjodah/bjodahimg:latest
git:
    path: github.com/bjodah/pyodesys
env:
  - MY_SERVER=pyodesys@hera.physchem.kth.se
script:
  - if [[ "$DRONE_BRANCH" =~ ^v[0-9]+.[0-9]?* ]]; then export PYODESYS_RELEASE_VERSION=$DRONE_BRANCH; echo ${PYODESYS_RELEASE_VERSION} | tail -c +2 > __conda_version__.txt; fi
  - pip install --user pyodeint pycvodes pygslodeiv2 pymbolic pysym
  - pip3 install --user pyodeint pycvodes pygslodeiv2 pymbolic pysym
  - PYTHONPATH=$(pwd) ./scripts/run_tests.sh --cov pyodesys --cov-report html
  - python2 setup.py sdist
  - pip install dist/*.tar.gz
  - (cd examples/; ipython2 nbconvert --to=html --ExecutePreprocessor.enabled=True --ExecutePreprocessor.timeout=300 *.ipynb)
  - (cd examples/; ../scripts/render_index.sh *.html)
  - ./scripts/generate_docs.sh
  - ./scripts/coverage_badge.py htmlcov/ htmlcov/coverage.svg
  - ssh "${MY_SERVER}" "mkdir -p ~/public_html/$DRONE_BRANCH"
  - scp -r doc/_build/html dist/* htmlcov/ examples/ ${MY_SERVER}:~/public_html/$DRONE_BRANCH
  - touch doc/_build/html/.nojekyll
  - git config --global user.name "drone"
  - git config --global user.email ${MY_SERVER}
  - if [[ "$DRONE_BRANCH" == "master" ]]; then ./scripts/github_upload.sh doc/_build/html bjodah pyodesys gh-pages; fi
  - if [[ "$DRONE_BRANCH" == "master" ]]; then scp -r benchmarks/* ${MY_SERVER}:~; fi
  - if [[ "$DRONE_BRANCH" == "master" ]]; then ssh ${MY_SERVER} 'source /etc/profile; asv run -k -e >asv-run.log; asv publish>asv-publish.log'; fi
