build:
  image: bjodah/bjodahimg16dev:latest
  commands:
    - bash -c '[[ $(python setup.py --version) =~ ^[0-9]+.* ]]'
    - conda config --add channels symengine/label/dev
    - conda config --add channels bjodah
    - ./scripts/ci.sh pyodesys
    - bash -c "source activate test3; python -m pip install .[all] gr"
    - bash -c "source activate test3; PYTHONPATH=$(pwd) ./scripts/render_notebooks.sh"
    - bash -c "source activate test3; ./scripts/generate_docs.sh"
    - bash -c "source activate test3; ./scripts/prepare_deploy.sh"

deploy:

  rsync:
    host: hera.physchem.kth.se
    port: 22
    user: pyodesys
    source: deploy/
    target: ~
    recursive: true
    delete: false
