build:
  image: bjodah/bjodahimgdev:latest
  commands:
    - conda config --add channels bjodah
    - conda config --add channels symengine/label/dev
    - ./scripts/ci.sh pyodesys
    - (cd examples/; ipython2 nbconvert --debug --to=html --ExecutePreprocessor.enabled=True --ExecutePreprocessor.timeout=300 *.ipynb)
    - (cd examples/; ../scripts/render_index.sh *.html)
    - ./scripts/generate_docs.sh
    - ./scripts/prepare_deploy.sh

deploy:

  rsync:
    host: hera.physchem.kth.se
    port: 22
    user: pyodesys
    source: deploy/
    target: ~
    recursive: true
    delete: false
