build:
  image: bjodah/bjodahimg16:v1.2
  commands:
    - bash -c '[[ $(python setup.py --version) =~ ^[0-9]+.* ]]'
    - ./scripts/ci.sh pyodesys
#    - ./scripts/ci_conda.sh pyodesys
    - ./scripts/prepare_deploy.sh
    - if grep "DO-NOT-MERGE!" -R . --exclude ".drone.yml"; then exit 1; fi

deploy:

  rsync:
    host: hera.physchem.kth.se
    port: 22
    user: pyodesys
    source: deploy/
    target: ~
    recursive: true
    delete: false
