{% set name = "pyodesys" %}
{% set version = "0.7.0.git" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  number: 0

requirements:
  build:
    - python
  run:
    - python
    - numpy
    - sym
    - sympy
    - scipy
    - appdirs

test:
  imports:
    - {{ name }}
  requires:
    - pytest
    - scipy
    - pyodeint
    - pygslodeiv2
    - pycvodes
    - pycompilation
    - pycodeexport
    - python-symengine
    - symcxx
    - pysym
  commands:
    - python -m pytest --pyargs {{ name }}

about:
  home: https://github.com/bjodah/{{ name }}
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Straightforward numerical integration of systems of ordinary differential equations'
  doc_url: https://bjodah.github.io/{{ name }}

extra:
  recipe-maintainers:
    - bjodah
