{% set name = "pyodesys" %}
{% set version = "0.10.0.git" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - sym
    - sympy
    - scipy
    - appdirs

test:
  imports:
    - {{ name }}
  requires:
    - python
    - numpy
    - sym
    - sympy
    - scipy
    - appdirs
    - pytest
    - pyodeint
    - boost
    - pygslodeiv2
    - pycvodes
    - pycompilation
    - pycodeexport
    - python-symengine
    - symcxx
    - pysym
    - matplotlib

about:
  home: https://github.com/bjodah/{{ name }}
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Straightforward numerical integration of systems of ordinary differential equations'
  doc_url: https://bjodah.github.io/{{ name }}/latest

extra:
  recipe-maintainers:
    - bjodah
