package:
    name: pyodesys
    version: 0.6.0.git

source:
    path: ../

build:
    number: 0

requirements:
    build:
        - python
    run:
        - python
        - numpy
        - sympy
        - scipy

test:
    imports:
        - pyodesys
    requires:
        - pytest
        - scipy
        - pyodeint
        - pygslodeiv2
        - pycvodes

about:
    home: https://github.com/bjodah/pyodesys
    license: BSD
